name: aronnax
description: Especialized EMR for psychologists.
 
publish_to: 'none' 

 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

 
dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  google_fonts: ^6.1.0
  analyzer: ^6.2.0
  js: ^0.6.3
  provider: ^6.0.2
  mysql1: ^0.20.0
  file_picker: ^6.1.1
  pdf: ^3.6.5
  crypt: ^4.2.1
  font_awesome_flutter: ^10.1.0
  path_provider: ^2.0.11
  drift: ^2.2.0
  sqlite3_flutter_libs: ^0.5.10
  flutter_riverpod: ^2.0.2
  country_state_city: ^0.1.3
  email_validator: ^2.1.17
  table_calendar: ^3.0.8
  flutter_localizations:
    sdk: flutter
  icons_launcher: ^2.1.0
  dio: ^5.1.1
  fl_chart: ^0.66.0
  url_launcher: ^6.1.11
  encrypt: ^5.0.1
 
  

dev_dependencies:
 
  build_runner: ^2.1.7
  drift_dev: ^2.2.0+1
 
  flutter_lints: ^3.0.1
  msix: ^3.14.2
 
flutter:
  generate: true
 
  uses-material-design: true
  assets:
  - assets/img/planta.png
  - assets/img/unknown-user.png
  - assets/img/flutter.png
  - assets/img/welcome.png
  - assets/img/choose.png
  - assets/img/create.png
  - assets/img/finish.png
  - assets/img/flowers_cover.png
  - assets/img/flowers2.png
  - assets/img/contact.png
  - assets/img/aronnax-icon-light.png
  - assets/img/aronnax-icon-dark.png
 

icons_launcher:
  image_path: 'assets/img/aronnax-icon-light.png'
  platforms:
    windows:
      enable: true
    linux:
      enable: true
    macos:
      enable: true

msix_config:
  display_name: Aronnax
  publisher_display_name: Aronnax
  identity_name: Aronnax.aronnax
  msix_version: 1.0.0.0
  capabilities: internetClient
  file_extension: .arnx
