name: aronnax
description: A clinical history and patients management for psychologists.
 
publish_to: 'none' 

 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

 
dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  google_fonts: ^3.0.1
  analyzer: ^5.2.0
  js: ^0.6.3
  provider: ^6.0.2
  mysql1: ^0.20.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  file_picker: ^5.2.2
  pdf: ^3.6.5
  hive_generator: ^2.0.0
  crypt: ^4.2.1
  font_awesome_flutter: ^10.1.0
  path_provider: ^2.0.11
  drift: ^2.2.0
  sqlite3_flutter_libs: ^0.5.10
  flutter_riverpod: ^2.0.2
  country_state_city: ^0.1.3
  email_validator: ^2.1.17
  table_calendar: ^3.0.8
  

dev_dependencies:
 
  build_runner: ^2.1.7
  drift_dev: ^2.2.0+1
 
  flutter_lints: ^2.0.1
 
flutter:
 
  uses-material-design: true
  assets:
  - assets/img/planta.png
  - assets/img/unknown-user.png
  - assets/img/flutter.png
  - assets/img/welcome.png
  - assets/img/choose.png
  - assets/img/create.png
  - assets/img/finish.png
  - assets/img/flowers_cover.png
  - assets/img/flowers2.png
  - assets/img/contact.png
  - assets/img/aronnax-icon-light.png
  - assets/img/aronnax-icon-dark.png
 