name: aronnax
description: Especialized EMR for psychologists.

publish_to: "none"

version: 0.1.1+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: any
  google_fonts: ^6.1.0
  analyzer: ^6.2.0
  js: ^0.7.1
  provider: ^6.0.2
  mysql1: ^0.20.0
  file_picker: ^8.0.0+1
  pdf: ^3.6.5
  crypt: ^4.2.1
  font_awesome_flutter: ^10.1.0
  path_provider: ^2.0.11
  drift: ^2.2.0
  sqlite3_flutter_libs: ^0.5.10
  flutter_riverpod: ^2.0.2
  country_state_city: ^0.1.3
  email_validator: ^3.0.0
  table_calendar: ^3.0.8
  flutter_localizations:
    sdk: flutter
  icons_launcher: ^2.1.0
  dio: ^5.1.1
  fl_chart: ^0.68.0
  url_launcher: ^6.1.11
  encrypt: 5.0.1

  path: any
  uuid: ^4.3.3
  supabase_flutter: ^2.4.0
  flutter_rating_bar: ^4.0.1
dev_dependencies:
  build_runner: ^2.1.7
  drift_dev: ^2.2.0+1

  flutter_lints: ^4.0.0

flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/img/welcome.png
    - assets/img/choose.png
    - assets/img/create.png
    - assets/img/aronnax-icon-light.png
    - assets/img/aronnax-icon-dark.png
    - assets/img/finish.png

icons_launcher:
  image_path: "assets/img/aronnax-icon-light.png"
  platforms:
    windows:
      enable: true
    linux:
      enable: true
    macos:
      enable: true
